### ISSUE TITLE
SCANsat support

### ISSUE THREAD

**Issue by DMagic1** [ShotgunNinja/Kerbalism#1]
I see in your code comments that SCANsat scanning isn't disabled when out of EC, is that accurate? It looks like your code should work (though it would probably be best to cache the SCANcontroller object rather than running through the whole reflection thing every time).

The only problem with disabling scanning this way is that it is not uncommon to run out of EC while in a planet's shadow. SCANsat has a very kludgy way of handling this; continuously trying to reactivate scanning unless the user manually disables scanning.

Having to constantly switch back to a vessel to reset the scanners because you don't have enough batteries would get really old. Coming up with a better solution to how it is currently handled has been on my list since I picked up the project, but I've never spent much time on it. If you have any ideas I would love to hear them (other than just telling people to pack more batteries, as I don't see running out of power temporarily as a major issue, since it really only delays acquiring a full scan).

Also, SCANsat resource scanners use a different module, "ModuleSCANresourceScanner" but it inherits from the SCANsat module and uses the same fields and methods for scanning.

**Comment by ShotgunNinja** [comment]
Hi, sorry that comment is obsolete... the mod does indeed disable the scanner when the vessel is out of EC in the background. I set the '_scanning_' field value to false in the ProtoPart and call the _SCANcontroller::removeVessel()_ function using reflection.

I agree re-enabling the scanner in background automatically if EC comes back is desiderable. Looks like I should be able to pull this through by calling _registerSensor_ pretty much exactly like its done in _SCANcontroller::OnLoad()_. I'll look into it for the next version.

I didn't realize the resource scanner used a different module. Looks like it will just work (tm) out of the box the way I'm interacting with it, I'll test it.

SCANcontroller isn't cached because its used only in the single simulation step when EC became not enough.

Anyway, thanks for the feedback and also thanks for your work on one of my favourite mod!

**Comment by ShotgunNinja** [comment]
I added support for resource scanners, both for background consumption as well as in the planner. Also made the detection of deployed state in the planner more robust. Will push them in the next version.

**Comment by DMagic1** [comment]
Actually I'm thinking that SCANcontroller.removeVessel is probably not the best method to handle the issue; it simply removes all scanners on that vessel from SCANsat's tracker, but doesn't do anything about the actual part module state.

It might be better to use the methods from the Part Module: [registerScanner() and unregisterScanner()](https://github.com/DMagic1/SCANsat/blob/dev/SCANsat/SCAN_PartModules/SCANsat.cs#L390-L403). As long as the module (or protomodule) has the correct KSP Field values loaded those should handle adding and removing the individual scanners from SCANsat's tracker. And it will avoid having to go through SCANcontroller.

Here is where the module handles trying to restart the scanner after it [runs out of power](https://github.com/DMagic1/SCANsat/blob/dev/SCANsat/SCAN_PartModules/SCANsat.cs#L134-L187). It uses the powerIsProblem flag to turn the scanner back on; I added a short timer to delay the restart, which seems to fix the issue of not being able to stop the scanner once you are out of power. I imagine something similar would work fine for background processing.

**Comment by ShotgunNinja** [comment]
Unfortunately the ProtoModules are just a glorified ConfigNode. I can only use non-static methods for them and in general I'm limited to reading and changing values from the ProtoModule.

So for the two methods _registerScanner()_ and _unregisterScanner()_ I can't call them directly (there is no object to speak of). I'll have to parse all the values from the strings stored in the ProtoModule and then call _SCANcontroller.controller.{un}registerSensor()_.

I used _removeVessel_ instead of _unregisterSensor_ because the former doesn't require to get _SensorType_ using reflection (and I was lazy that day i guess...).

For the part state, I set the field '_scanning_' to false directly in the ProtoModule to fool your SCANsat module into the disabled state when it goes live again (meanwhile the scanning is stopped in the background by my call to removeVessel). 

I'm not touching the _powerIsProblem _field because it isn't serializable (so its not in the ProtoModule), I can't read or modify it when your module is unloaded (and OnStart reset it anyway).

I think I'll try to just set '_scanning_' back to true in the ProtoModule and call _controller.registerScanner()_. This way the scanning does start as soon as EC is back, with the vessel unloaded. And then when its loaded the SCANsat module it will be fooled again into the enabled state. It will never that coming :) Cheers.

**Comment by DMagic1** [comment]
I didn't really check this very well, since 1.1 was released just as I finished, but I added [these two methods](https://github.com/S-C-A-N/SCANsat/blob/release/SCANsat/SCANutil.cs#L185-L259) to the latest release of SCANsat (v16.0).

They are put in together with all of the other external API methods in SCANUtil.

If you just give them the Vessel reference, the ProtoPartModuleSnapShot, and the Part prefab, it should handle all of the registering and unregistering. They should be able to get the scanner type and properties from the part prefab and use those to correctly un/register a sensor. It also updates the "scanning" status for the protomodule.

**Comment by ShotgunNinja** [comment]
Perfect! Thank you for this, it's gonna make my job easier and the whole thing more robust. I'll let you know if there are any eventual problems, 1.1 is out, what? Oh sheet.

**Comment by ShotgunNinja** [comment]
Dmagic I found a little problem in your code.

`if (!prefab.Modules.Contains<SCANsat.SCAN_PartModules.SCANsat>()
  || !prefab.Modules.Contains<ModuleSCANresourceScanner>()) return false;`

should be

`if (!(prefab.Modules.Contains<SCANsat.SCAN_PartModules.SCANsat>()
  || prefab.Modules.Contains<ModuleSCANresourceScanner>())) return false;`

as one of the conditions is always going to fail otherwise.

**Comment by DMagic1** [comment]
Whoops, I figured I would miss something. Try this .dll, I think the moduleName check will also have the same problem, so I fixed that too:

[https://www.dropbox.com/s/p45h8rretgycrum/SCANsat.dll?dl=0](https://www.dropbox.com/s/p45h8rretgycrum/SCANsat.dll?dl=0)

I expect that there will be a KSP 1.1.1, so I'll probably have to release again in a week or two anyway.

**Comment by ShotgunNinja** [comment]
Thanks. No rush at all, I'll use this dll during development and wait to release the more robust code into the wild after your own release.

**Comment by ShotgunNinja** [comment]
I see your new release. I'm using your new API in next version, this can be closed now.

Thanks for the help! Cheers.
