### ISSUE TITLE
Erroneous warnings displays

### ISSUE THREAD

**Issue by OzoneGrif** [ShotgunNinja/Kerbalism#13]
I've seen two cases of erroneous warnings (the red popup with "life support is off" or "we lost control").

When the command pod's reserves falls to zero, but there are other storage on the ship, sometimes you get the warning "no food" or "no energy", but when you check the ship, everything is fine since there are reserves in other parts.

I've also seen the warnings appear right after the ship's destruction. This one is minor but slightly frustrating :)

**Comment by ShotgunNinja** [comment]
For the spurious resources warnings, it was about a bug in stock on how resource flow flag is handled. It should be fixed in 1.1.2 (haven't checked) but if not, I have a workaround ready to use in place of that.

For the warning right after ship destruction, its possible your storage was destroyed before the crewed parts and so my system detected one of your manned ships was without a vital resource... There are a lot of corner cases happening for a split second during a ship explosion. I'll try to find a way around this, eventually.

Closing this for now, raise another issue in 0.9.9.5 if the resource flow problem is still present. Thank you for your feedback.
