### ISSUE TITLE
Custom Greenhouse stuck on 199d growth

### ISSUE THREAD

**Issue by Quartz101** [ShotgunNinja/Kerbalism#26]
Patch: http://pastebin.com/rpWrzvrJ

I am attempting to patch UKS to work w/ Kerbalism. It works, except the MKS (haven't tested OKS) "Agricultural Module" (called MKV_AgModule in the patch) won't produce food, as it is stuck on 199d left, or 177d 4h with a full supply of crap, lights full. Note that the crap was generated w/ HyperEdit, I don't see a way to CREATE crap.

**Comment by ShotgunNinja** [comment]
Thanks for working on this patch!

Maybe the problem is the double Crap resource that is added to MKV_AgModule, albeit I can't see how that minor issue should prevent food growth above a certain point.

In fact, there is no need to add the Crap resource to the greenhouse parts at all. This changed recently, as adding it to the greenhouse part can lead to problems depending on the profile the player choose to use (where the waste resource name is arbitrarily choose by the player/profile). The waste resources are now added to the manned pods directly in-code, automatically . Also in next version the visibility and density of waste resources can be set by the Rule (for the same reasons), so the suggested method is to not tweak the resource definitions directly.

Note that crap is not required for greenhouse growth and it only act as a bonus when present.

For the scrubber, one will be added to all manned parts automatically from the profile, with appropriate co2_rate and waste resource name. So there is no need to add one by hand unless the rates need to be tweaked for that particular part, or the part is not manned or has no command module.

For the entertainment, in my opinion your rates are a bit too high and should be lowered to something between 1.5 and 2.5, unless you see those parts as extremely effective at reducing stress rate. For comparison the cupola is 1.8 and the gravity ring at max speed is 2.5.

Let me know if removing the 'double crap' from the greenhouse in question fix the issue, otherwise I'll look into this more in depth. Thanks again.

**Comment by Quartz101** [comment]
Ok! Thanks!

**Comment by Quartz101** [comment]
Nope, that doesn't fix the problem. But crap production is fixed!

**Comment by ShotgunNinja** [comment]
There was a problem in how the sun visibility is determined at extreme timewarp, that is fixed in 1.0.0.0 (soon to be released). Essentially the sun at every simulation step could have been visible or not, depending on where the step was occurring during the orbit (or planet rotation if on the surface). This influenced the growth rate of greenhouses too, and indirectly the time to harvest estimate (that is calculated from the growth rate at last simulation step). To verify this, check if the harvest ETA is messed up only at the 2 highest timewarps.

**Comment by Quartz101** [comment]
Ok. But however, I tested it with both physics and timewarp. But i'll test anyways... Also, any betas for 1.0?

**Comment by Quartz101** [comment]
Ok.. after testing a bit, the normal Kerbalism greenhouse has sorta-correct ETA, but the MKV Greenhouse gets stuck on 199d.

**Comment by ShotgunNinja** [comment]
A new version has been released. Please confirm if the problem is still present.

**Comment by Quartz101** [comment]
Yep, 1.0.0.0 fixed it.

**Comment by Quartz101** [comment]
btw, incase you're wondering, the finished version is located here: http://spacedock.info/mod/730/UKS-Kerbalism%20Patch
