### ISSUE TITLE
Question about adding back the internal antenna

### ISSUE THREAD

**Issue by Maxzhao1999** [ShotgunNinja/Kerbalism#61]
I wanted to add the internal antenna for the command pads but I don't know what to do with the code, if I just add it like this will it be a new part? Can I just remove the "cost" since it's internal? I'm new to configuring and it seems to me that everything is wrong with these code I wrote. I love your mod btw :D
```
// ============================================================================
// Remove internal antennas from pods
// ============================================================================

@PART[*]:HAS[@MODULE[ModuleCommand]]:NEEDS[FeatureSignal]:FOR[Kerbalism]
{
  MODULE
  { 
   name = Antenna
   type = high_gain
   cost = 0.1
   dist = 5e5
   rate = 0.010
}


  !MODULE[ModuleDataTransmitter] {}
}`

**Comment by Maxzhao1999** [comment]
Just read the sourcecode and realised cost does not mean funds, so maybe this does not to be altered, but is everything else okay?

**Comment by ShotgunNinja** [comment]
_cost_ in Antenna module refer to the ElectricCharge per-second required for transmitting data.

Your patch is saying:
- modify all parts, irregardless of their name (@PART[*])
- but only if they have a module with name ModuleCommand (:HAS[@MODULE[ModuleCommand]])
- and only if the signal feature is enabled (:NEEDS[FeatureSignal])

:FOR[Kerbalism] is not required, if this is a personal tweak (that I'm assuming is the case).

The Antenna module values are okay from a technical perspective. Balance wise maybe you could use a _low_gain_ antenna instead of an _high_gain_ one.

**Comment by Maxzhao1999** [comment]
Thank you very much! I'll make changes to that👌

**Comment by YaarPodshipnik** [comment]
If you are writing patches that edit all the parts, it's useful to make sure you don't spam the same module multiple times. In your case, if there was a pod that already has in-built kerbalism support, and a specifically configured internal antenna, it would get another one from your patch!. To prevent that you can use the HAS condition, turning your first line into this:

```
@PART[*]:HAS[@MODULE[ModuleCommand],!MODULE[Antenna]]:NEEDS[FeatureSignal]
```
