### ISSUE TITLE
Difficulty settings menu (feature request)

### ISSUE THREAD

**Issue by MuhsinFatih** [ShotgunNinja/Kerbalism#77]
Like many other mods do, could you put a set of options in the game's difficulty settings? I love the concept of this mod, however I don't like how little resources containers can have. I mean for example I want to go for a 3 years long trip with 3-5 kerbals, It requires absurdly many life support parts that at the end my ship is a giant taco bin. I want to adjust the rate at which these supplies are consumed but settings file is too complicated (really you are documenting, not commenting for dev. purposes, or should I say you shouldn't be?). 
Also changing settings requires restarting the game which makes tweaking them extremely annoying (I have roughy 3 minutes of loading, with a freking 2gb/s ssd). 

Man I love this mod, I would have created a pull request with the options menu if I knew how to develop unity mods for kerbal. However requesting the feature is the only thing I can do now, so sorry about that :).

**Comment by lordcirth** [comment]
Just checking, for this 3 year vessel, are you using recycling like greenhouses?

**Comment by MuhsinFatih** [comment]
Well that was an example I made up :) Actually after not playing so long I realized there were so many changes that it was worth starting from scratch. So there's no such ship yet :)
My point is that not everyone would want the same level of difficulty. This mod is really cool but personally, sometimes I find it so hard that it gets annoying. Maybe this is because I have many other mods some of which also make the game harder.
Btw I think TAC life support could be a model for my request. It has a menu exactly as I described. Though options like 'easy' 'moderate' 'hard' could also be even better but that might be too much asking I guess :)

**Comment by ShotgunNinja** [comment]
In-game options like you see in other mods are not possible here.

The reason is that options need to be parsed before MM start patching, at KSP loading time. The information parsed from the options is then used to inject MM patches on-the-fly. These in turns are used by other MM patches (shipped with this mod, and by some third-party mods) to do conditional patching based on the feature set and profile choosen by the user.

This is a very flexible system, that allow this mod to be reconfigured in many fundamental different ways and still have some kind of support by third-party mods. See for example how this architecture is used by KPBS to add extensive support to this mod.

One thing I could do, and I was thinking of doing, is to have some kind of graphical editor for the settings, that can pop out at KSP loading time (before MM patches are applied). In there you could change the settings, profile, features. But then KSP will need to be rebooted anyway when you change something, because the MM cache need to be invalidated (because the patch set changed). So you can see why I didn't implement this already, because fundamentally there is no way to avoid the KSP reboot after settings change with current architecture.
